spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        time_zone: Asia/Seoul
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  config:
    activate:
      on-profile: local

  datasource:
    maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/indidb
    username: indiadmin
    password: indiadmin
    driver-class-name: org.postgresql.Driver

  logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: debug

jwt:
  secretKey: asdokjfqlekrthlbandglkasujdriqkwejnlkrtajf123!(sdfioja0-123jkladsfajipo~~~assdfa

  access:
    expiration: 3600000
    header: Authorization

  refresh:
    expiration: 4320000000
    header: ReAuthorization

#oauth:
#  kakao:
#    client_id: e646a7ca71e42854df6c346e0fb68dac
#    client_secret: 0TKyAtTtOAuhCF3fxkVLz6Ds0gR8W1tN
#    redirect_uri: http://localhost:3000/kakao/callback
#    scope: profile_nickname, account_email
#
#  naver:
#    client-id: JKIPRpLStQVrXKik5JFL
#    client-secret: onBVovUzAW
#    redirect-uri: http://localhost:3000/naver/callback
#    scope: name, email
#    state: aaoipqneptnakdsf
#
#  google:
#    client-id: 957894981574-ikejc0ifd0gce62d33chk9617bf0e72n.apps.googleusercontent.com
#    client-secret: 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
#    redirect_uri: http://localhost:3000/google/callback
#    scope: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email


