spring:
  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        time_zone: Asia/Seoul
        format_sql: false
        show_sql: false
        default_batch_fetch_size: 1000
    database-platform: org.hibernate.dialect.PostgreSQLDialect

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod

---
spring:
  config:
    activate:
      on-profile: local
